server:
  port: 8080

spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:hello-response-entity;
    driver-class-name: org.h2.Driver
    username: abc
    password: abc
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    open-in-view: true
    #hibernate:
      #ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  #file:
  #path: /data/logs/hello-response-entity
  #max-size: 50MB
  #max-history: 7
  level:
    root: debug
    org.hibernate.SQL: debug